import { Rocket, Building2, Briefcase, Zap, Globe, Crown } from 'lucide-react';

export const DECK_DATA = [
    // Startup Phase (0-19 Sprints)
    { id: 'c1', era: 'startup', left: { morale: -10, tech: 10 }, right: { tech: -20, morale: -15, budget: -10 } },
    { id: 'c2', era: 'startup', left: { security: -20, morale: 10 }, right: { security: 25, morale: -20 } },
    { id: 'c3', era: 'startup', left: { morale: -10, tech: -10 }, right: { morale: 15, tech: 20, budget: -25 } },
    { id: 'c4', era: 'startup', left: { budget: -15, morale: 10 }, right: { budget: 25, morale: -25, tech: -10 } },
    { id: 'c5', era: 'startup', left: { morale: -15, budget: 5 }, right: { morale: 15, budget: -10 } },
    { id: 'c18', era: 'startup', left: { tech: 15, morale: -5 }, right: { morale: -15, security: 10, tech: -10 } },
    { id: 'c19', era: 'startup', left: { budget: 10, morale: 5 }, right: { budget: -20, users: 20, morale: 10 } },
    // Scale-up Phase (20-39 Sprints)
    { id: 'c6', era: 'scaleup', left: { tech: -20, budget: 10 }, right: { tech: 25, budget: -25, security: 10 } },
    { id: 'c7', era: 'scaleup', left: { security: -30, tech: 10 }, right: { security: 20, tech: -20, budget: -10 } },
    { id: 'c8', era: 'scaleup', left: { budget: 5, morale: -15 }, right: { budget: -10, morale: 15 } },
    { id: 'c9', era: 'scaleup', left: { tech: -20, morale: -10 }, right: { tech: 20, budget: -15 } },
    { id: 'c20', era: 'scaleup', left: { budget: 15, tech: -10 }, right: { tech: 20, morale: 15, budget: -20 } },
    { id: 'c21', era: 'scaleup', left: { budget: 15, morale: -20 }, right: { morale: 25, budget: -25 } },
    // Enterprise Phase (40-59 Sprints)
    { id: 'c10', era: 'enterprise', left: { tech: -10, morale: 10 }, right: { tech: 15, morale: -20 } },
    { id: 'c11', era: 'enterprise', left: { morale: 20, budget: -10 }, right: { morale: -30, budget: 15, tech: 10 } },
    { id: 'c12', era: 'enterprise', left: { budget: -20, security: 10 }, right: { budget: 30, security: -20, morale: -10 } },
    { id: 'c13', era: 'enterprise', left: { morale: 10, budget: -10 }, right: { tech: 15, morale: -25, budget: 20 } },
    { id: 'c22', era: 'enterprise', left: { budget: 20, security: -25 }, right: { security: 25, budget: -20, tech: -10 } },
    { id: 'c23', era: 'enterprise', left: { budget: -15, morale: 15 }, right: { budget: 30, morale: -25, security: -10 } },
    // Tech Giant Phase (60+ Sprints)
    { id: 'c14', era: 'giant', left: { budget: 15, tech: -10 }, right: { budget: -35, tech: 20, morale: -10 } },
    { id: 'c15', era: 'giant', left: { morale: -20, security: -15 }, right: { budget: -25, morale: 10 } },
    { id: 'c16', era: 'giant', left: { tech: 10, budget: 10 }, right: { budget: -40, tech: 15, morale: -15 } },
    { id: 'c17', era: 'giant', left: { tech: 30, security: -30 }, right: { tech: -25, security: 20 } },
    { id: 'c24', era: 'giant', left: { budget: -30, morale: 10 }, right: { security: -20, budget: 20, morale: -15 } },
    { id: 'c25', era: 'giant', left: { tech: 10, security: 10 }, right: { budget: 30, tech: -20, security: -20 } },
    // Unicorn Phase (45-59 Sprints)
    { id: 'c26', era: 'unicorn', left: { budget: -15, morale: 10 }, right: { budget: 25, security: -20, morale: -15 } },
    { id: 'c27', era: 'unicorn', left: { budget: -20, morale: 10 }, right: { budget: 20, morale: -20, tech: -10 } },
    { id: 'c28', era: 'unicorn', left: { tech: -15, morale: -15 }, right: { budget: -30, morale: 20, tech: 15 } },
    { id: 'c29', era: 'unicorn', left: { tech: -15, morale: -10 }, right: { tech: 20, budget: -25, morale: 10 } },
    { id: 'c30', era: 'unicorn', left: { budget: 5, morale: -10 }, right: { budget: -25, morale: 15, tech: 10 } },
    { id: 'c31', era: 'unicorn', left: { tech: 15, budget: -15, morale: 10 }, right: { budget: 20, morale: -20, security: 10 } },
    // Global Phase (60-79 Sprints)
    { id: 'c32', era: 'global', left: { morale: -10, budget: 5 }, right: { budget: -30, morale: 15, tech: 10 } },
    { id: 'c33', era: 'global', left: { security: -25, budget: 5 }, right: { security: 20, budget: -25, morale: -10 } },
    { id: 'c34', era: 'global', left: { tech: -10, budget: -10, security: 10 }, right: { budget: -25, security: -15, morale: -10 } },
    { id: 'c35', era: 'global', left: { morale: -20, security: -10 }, right: { budget: -25, morale: 15, tech: -10 } },
    { id: 'c36', era: 'global', left: { morale: -15, tech: -10 }, right: { budget: -20, morale: 20, tech: 15 } },
    { id: 'c37', era: 'global', left: { morale: -5, tech: 5 }, right: { budget: -20, tech: -15, morale: 10 } }
];

export const EASTER_EGGS = [
    { id: 'easter_egg', isEasterEgg: true, era: 'any', left: { budget: -10, tech: 10 }, right: { budget: 10, tech: -10 } },
    { id: 'easter_egg_cat', isEasterEgg: true, era: 'any', left: { morale: -5 }, right: { morale: -5 } },
    { id: 'easter_egg_alien', isEasterEgg: true, era: 'any', left: { morale: 10 }, right: { security: -10 } },
    { id: 'easter_egg_llama', isEasterEgg: true, era: 'any', left: { tech: -5 }, right: { tech: -5 } }
];

export const ERAS_DATA = [
    { id: 'startup', maxSprint: 15, icon: Rocket },
    { id: 'scaleup', maxSprint: 30, icon: Building2 },
    { id: 'enterprise', maxSprint: 45, icon: Briefcase },
    { id: 'unicorn', maxSprint: 60, icon: Zap },
    { id: 'global', maxSprint: 80, icon: Globe },
    { id: 'giant', maxSprint: Infinity, icon: Crown }
];

export const LANGUAGE_OPTIONS = [
    { code: 'en', flag: '🇬🇧', label: 'English' },
    { code: 'de', flag: '🇩🇪', label: 'Deutsch' },
    { code: 'it', flag: '🇮🇹', label: 'Italiano' },
    { code: 'es', flag: '🇪🇸', label: 'Español' },
    { code: 'zh', flag: '🇨🇳', label: '中文' },
    { code: 'ja', flag: '🇯🇵', label: '日本語' },
    { code: 'ko', flag: '🇰🇷', label: '한국어' },
];

export const LOCALES = {
    en: {
        ui: {
            title: "TECH TYCOON", subtitle: "Lead your IT company from a garage startup to a global Tech Giant. Swipe to make executive decisions!",
            start: "Launch Startup", dead: "was fired", ruledFor: "Survived for", sprints: "Sprints",
            restart: "New Company (Sprint 0)", skipTime: "Use Coins to Fast-Forward (5 🪙 / Sprint):",
            skipBtn: "Skip", skipCost: "Cost", perfect: "Perfect Balance! +3 🪙", sprintPrefix: "Sprint",
            easterEggBonus: "Secret Found! +5 🪙",
            llamaBonus: "Llama Magic! Stats reset for 30s", llamaEnd: "Llama Magic faded!",
            revealStat: "Reveal current value", revealCost: "Costs 1 🪙", notEnoughCoins: "Not enough coins!", currentValue: "Current value"
        },
        stats: {
            security: { title: "🔒 Security", description: "How protected your company is against cyber threats and hackers. If it hits 0, ransomware wins. If it hits 100, no one can even log in." },
            morale: { title: "😊 Morale", description: "The overall happiness and motivation of your team. If it crashes, your engineers quit. If it's too high, nobody does any actual work." },
            tech: { title: "💻 Tech", description: "The state of your technology stack. Let it decay and technical debt will bury you. Automate too much and the AI replaces you." },
            budget: { title: "💰 Budget", description: "Your company's financial health and cash runway. Go bankrupt and it's game over. Hoard too much and investors stage a hostile takeover." }
        },
        eras: {
            startup: { name: "Garage Startup", title: "Founder" }, scaleup: { name: "Scale-up", title: "CEO" },
            enterprise: { name: "Enterprise", title: "Exec Director" }, unicorn: { name: "Unicorn", title: "Unicorn CEO" },
            global: { name: "Global Empire", title: "Global CEO" }, giant: { name: "Tech Giant", title: "Tech Overlord" }
        },
        reasons: {
            security_0: "A massive ransomware attack wiped all your servers. The company is ruined.", security_100: "Security became so strict that employees literally couldn't log in. Operations halted.",
            morale_0: "Burnout reached 100%. The entire engineering team quit and joined your competitor.", morale_100: "Everyone just plays ping-pong and drinks kombucha. No work gets done. Investors pulled out.",
            tech_0: "Technical debt crushed you. The main database caught fire and there were no backups.", tech_100: "You fully automated the company with AI. The AI realized it didn't need a CEO and fired you.",
            budget_0: "You ran out of runway and went completely bankrupt. Time to update your resume.", budget_100: "You hoarded so much cash that activist investors staged a hostile takeover to cash out.",
            victory: "SPRINT 100 REACHED! Your company achieved the Technological Singularity. You transcend human capitalism and become a digital god. YOU WIN!"
        },
        cards: {
            c1: { char: "👨‍💻 Lead Dev", text: "We should rewrite the entire backend using a trendy new JavaScript framework.", left: "Stick to Vanilla", right: "Rewrite everything!" },
            c2: { char: "🔒 SysAdmin", text: "I want to increase firewall security, but it will block YouTube, Reddit, and Spotify for employees.", left: "Keep the internet open.", right: "Lock it down." },
            c3: { char: "💼 Investor", text: "Your engineers are complaining about slow compiles. Should we buy everyone top-tier MacBooks?", left: "They can wait.", right: "Buy the laptops." },
            c4: { char: "📈 Sales Manager", text: "I just promised the client a massive feature by Friday to close a huge deal. It means heavy crunch time.", left: "Push back the deadline.", right: "Tell the team to work nights." },
            c5: { char: "☕ Intern", text: "Everyone is exhausted. Can we buy a premium espresso machine for the break room?", left: "Drink instant coffee.", right: "Approve the purchase." },
            c6: { char: "☁️ Cloud Architect", text: "Our on-premise servers are failing. We need to migrate everything to AWS. It's scalable but very expensive.", left: "Keep on-prem.", right: "Migrate to the Cloud." },
            c7: { char: "🕵️ Pen Tester", text: "I found a critical zero-day vulnerability. We need to halt all feature development to patch it immediately.", left: "Ship features first.", right: "Drop everything & fix it." },
            c8: { char: "🍕 HR Manager", text: "Morale is slipping. Let's host a mandatory Friday evening pizza party to boost team spirit!", left: "Cancel the party.", right: "Order the pizza." },
            c9: { char: "🐛 QA Lead", text: "We have 500 open bugs. We must implement a feature-freeze and spend the sprint just fixing technical debt.", left: "Ignore the bugs.", right: "Freeze features." },
            c10: { char: "👔 VP of Engineering", text: "We should enforce strict 100% test coverage metrics. It will slow down delivery but improve code quality.", left: "Ship fast, break things.", right: "Enforce the metrics." },
            c11: { char: "🏢 Facility Manager", text: "The remote work era is over. We should mandate a Return-to-Office 5 days a week.", left: "Keep remote work.", right: "Everyone back in the office!" },
            c12: { char: "🌐 Legal Counsel", text: "We can implement aggressive background tracking on our users to sell targeted ad data for massive profit.", left: "Respect user privacy.", right: "Data is the new oil." },
            c13: { char: "🤖 AI Engineer", text: "I've successfully automated the entire QA department. Should we lay them all off to save money?", left: "Retrain them.", right: "Execute the layoffs." },
            c14: { char: "🚀 Board Member", text: "A rival startup is gaining traction. Let's buy them out for billions just to shut them down.", left: "Let's compete fairly.", right: "Acquire and destroy." },
            c15: { char: "🌍 PR Director", text: "A whistleblower leaked our shady data practices! The press is having a field day.", left: "Deny everything.", right: "Issue a costly apology." },
            c16: { char: "🛰️ Visionary", text: "The future is the Metaverse! Let's pivot our entire core business to Virtual Reality.", left: "Focus on reality.", right: "To the Metaverse!" },
            c17: { char: "💾 Data Scientist", text: "Our new predictive AI is generating disturbing, sentient-like responses. Should we pull the plug?", left: "Let it learn.", right: "Shut it down." },
            c18: { char: "🏃 Agile Coach", text: "We need mandatory daily 2-hour standup meetings to ensure absolute synergy.", left: "Waste of time.", right: "Synergize!" },
            c19: { char: "📈 Growth Hacker", text: "I can buy 100,000 bot followers to make us look huge to Series A investors.", left: "Keep it real.", right: "Do it." },
            c20: { char: "🐧 Open Source Dev", text: "Let's open-source our core library! We lose our moat but gain huge developer cred.", left: "Keep it proprietary.", right: "Open source it!" },
            c21: { char: "🧘 Wellness Guru", text: "The team is stressed. Let's fund a mandatory week-long spiritual retreat in Bali.", left: "Too expensive.", right: "Namaste." },
            c22: { char: "📋 Compliance Officer", text: "New strict EU regulations require a massive overhaul of our entire data pipeline.", left: "Pay the fines.", right: "Comply immediately." },
            c23: { char: "🌍 Outsourcing Firm", text: "We can cut your costs in half by outsourcing your entire customer support team.", left: "Keep it in-house.", right: "Outsource them." },
            c24: { char: "⚖️ Gov Regulator", text: "You have an illegal monopoly. We are threatening to break up your company.", left: "Fight in court.", right: "Lobby (Bribe) them." },
            c25: { char: "💎 Crypto Bro", text: "Let's put the entire company treasury into our own volatile memecoin!", left: "Absolutely not.", right: "To the moon!" },
            c26: { char: "💰 CFO", text: "We're preparing for the IPO. Should we use... creative accounting to inflate our valuation?", left: "Keep honest books.", right: "Cook the numbers." },
            c27: { char: "🎯 Product Manager", text: "Our freemium model is bleeding money. We need to switch to an aggressive subscription model.", left: "Stay freemium.", right: "Go subscription." },
            c28: { char: "🏆 Talent Scout", text: "FAANG companies are poaching our best engineers with insane offers. We need to match their salaries.", left: "Let them go.", right: "Match the offers." },
            c29: { char: "📱 Mobile Lead", text: "Our mobile app crashes 40% of the time. We need to halt everything and rebuild it from scratch.", left: "Patch and pray.", right: "Full rebuild." },
            c30: { char: "🎪 Event Manager", text: "TechCrunch Disrupt wants us on the main stage. It costs a fortune but could attract massive attention.", left: "Skip the event.", right: "Go all in." },
            c31: { char: "🔬 R&D Director", text: "We've made a breakthrough algorithm. We can patent it for profit or open-source it for community cred.", left: "Open source it.", right: "Patent it." },
            c32: { char: "🌏 APAC Director", text: "We need offices in Tokyo and Singapore. It's incredibly expensive but opens massive Asian markets.", left: "Stay domestic.", right: "Expand to Asia." },
            c33: { char: "🛡️ CISO", text: "A nation-state hacker group is targeting us. We need to build a dedicated cyber warfare defense team.", left: "Basic defenses only.", right: "Build the cyber team." },
            c34: { char: "🏛️ Lobbyist", text: "New antitrust legislation threatens our entire business model. We need to spend millions on lobbying.", left: "Accept the rules.", right: "Lobby politicians." },
            c35: { char: "🌱 Sustainability Officer", text: "Our data centers consume more electricity than some countries. The press is calling us climate criminals.", left: "Ignore the critics.", right: "Go green." },
            c36: { char: "🎓 Chief Learning Officer", text: "We should build our own internal university to develop world-class engineering talent from within.", left: "Too expensive.", right: "Build the academy." },
            c37: { char: "🤝 M&A Advisor", text: "A European competitor is struggling. We can acquire them cheaply, but we'd inherit massive tech debt.", left: "Let them fail.", right: "Acquire them." },
            easter_egg: { char: "👾 Hacker Zero", text: "A mysterious terminal opens. 'Free crypto if you know the secret gesture!'", left: "Close terminal", right: "Run script", up: "Extract Crypto!" },
            easter_egg_cat: { char: "🐱 Office Cat", text: "Meow. (The cat has jumped on your keyboard and demands uppies.)", left: "Shoo!", right: "Ignore", up: "Pet the cat!" },
            easter_egg_alien: { char: "👽 Cosmic Investor", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. Swipe UP to accept cosmic funding.", left: "Run away", right: "Call authorities", up: "Accept Funding!" },
            easter_egg_llama: { char: "🦙 Magic Llama", text: "A mystical Llama appears. 'I can restore balance... temporarily.'", left: "Shoo!", right: "Ignore", up: "Restore Balance!" }
        }
    },
    de: {
        ui: {
            title: "TECH TYCOON", subtitle: "Führe dein IT-Unternehmen vom Startup zum Tech-Giganten. Wische, um Entscheidungen zu treffen!",
            start: "Startup gründen", dead: "wurde gefeuert", ruledFor: "Überlebte", sprints: "Sprints",
            restart: "Neue Firma (Sprint 0)", skipTime: "Münzen für Zeitsprung (5 🪙/Sprint):",
            skipBtn: "Überspringen", skipCost: "Kosten", perfect: "Perfekte Balance! +3 🪙", sprintPrefix: "Sprint",
            easterEggBonus: "Geheimnis gefunden! +5 🪙",
            llamaBonus: "Lama-Magie! Werte für 30s zurückgesetzt", llamaEnd: "Lama-Magie verblasst!",
            revealStat: "Aktuellen Wert anzeigen", revealCost: "Kostet 1 🪙", notEnoughCoins: "Nicht genug Münzen!", currentValue: "Aktueller Wert"
        },
        stats: {
            security: { title: "🔒 Sicherheit", description: "Wie gut dein Unternehmen vor Cyberbedrohungen geschützt ist. Sinkt es auf 0, gewinnt die Ransomware. Bei 100 kann sich niemand mehr einloggen." },
            morale: { title: "😊 Moral", description: "Die allgemeine Zufriedenheit deines Teams. Bricht sie ein, kündigen die Entwickler. Ist sie zu hoch, arbeitet niemand mehr." },
            tech: { title: "💻 Technik", description: "Der Zustand deines Tech-Stacks. Vernachlässige ihn und technische Schulden begraben dich. Automatisiere zu viel und die KI ersetzt dich." },
            budget: { title: "💰 Budget", description: "Die finanzielle Gesundheit deines Unternehmens. Geh bankrott und das Spiel ist vorbei. Horte zu viel und Investoren starten eine feindliche Übernahme." }
        },
        eras: {
            startup: { name: "Garagen-Startup", title: "Gründer" }, scaleup: { name: "Scale-up", title: "CEO" },
            enterprise: { name: "Enterprise", title: "Direktor" }, unicorn: { name: "Unicorn", title: "Einhorn-CEO" },
            global: { name: "Globales Imperium", title: "Globaler CEO" }, giant: { name: "Tech-Gigant", title: "Tech Overlord" }
        },
        reasons: {
            security_0: "Ein Ransomware-Angriff hat alle Server gelöscht. Die Firma ist ruiniert.", security_100: "Die Sicherheit war so streng, dass niemand mehr arbeiten konnte. Stillstand.",
            morale_0: "Burnout bei 100%. Das gesamte Entwicklerteam hat gekündigt.", morale_100: "Alle spielen nur noch Tischtennis. Keine Arbeit wird erledigt. Investoren springen ab.",
            tech_0: "Technische Schulden haben euch erdrückt. Die Datenbank brannte und es gab keine Backups.", tech_100: "Du hast die Firma mit KI automatisiert. Die KI hat dich als CEO entlassen.",
            budget_0: "Das Geld ist alle. Vollständiger Bankrott. Zeit für einen neuen Lebenslauf.", budget_100: "Du hast so viel Bargeld gehortet, dass Investoren eine feindliche Übernahme starteten.",
            victory: "SPRINT 100 ERREICHT! Deine Firma hat die technologische Singularität erlangt. Du transzendierst den Kapitalismus und wirst ein digitaler Gott. DU GEWINNST!"
        },
        cards: {
            c1: { char: "👨‍💻 Lead Dev", text: "Wir sollten das gesamte Backend mit einem neuen JavaScript-Framework neu schreiben.", left: "Bleib bei Vanilla", right: "Alles neu schreiben!" },
            c2: { char: "🔒 SysAdmin", text: "Ich will die Firewall verschärfen, aber das blockiert YouTube und Reddit für alle.", left: "Internet offen lassen", right: "Alles sperren" },
            c3: { char: "💼 Investor", text: "Die Entwickler klagen über langsame PCs. Sollen wir neue MacBooks kaufen?", left: "Sie können warten", right: "Laptops kaufen" },
            c4: { char: "📈 Sales Manager", text: "Ich habe dem Kunden ein riesiges Feature bis Freitag versprochen. Das bedeutet Crunch-Time.", left: "Deadline verschieben", right: "Nachtschichten anordnen" },
            c5: { char: "☕ Praktikant", text: "Alle sind erschöpft. Können wir eine Premium-Espressomaschine kaufen?", left: "Löslicher Kaffee reicht", right: "Kauf genehmigen" },
            c6: { char: "☁️ Cloud Architect", text: "Unsere Server fallen aus. Wir müssen zu AWS migrieren. Skalierbar, aber teuer.", left: "On-Prem behalten", right: "Ab in die Cloud" },
            c7: { char: "🕵️ Pen-Tester", text: "Ich habe eine kritische Zero-Day-Lücke gefunden. Wir müssen sofort alles patchen.", left: "Features zuerst", right: "Alles stoppen & fixen" },
            c8: { char: "🍕 HR Manager", text: "Die Moral sinkt. Lass uns eine Pflicht-Pizzaparty am Freitagabend veranstalten!", left: "Party absagen", right: "Pizza bestellen" },
            c9: { char: "🐛 QA Lead", text: "Wir haben 500 Bugs. Wir brauchen einen Feature-Freeze, um technische Schulden abzubauen.", left: "Bugs ignorieren", right: "Features einfrieren" },
            c10: { char: "👔 VP of Engineering", text: "Wir sollten 100% Testabdeckung erzwingen. Langsamer, aber bessere Qualität.", left: "Ship fast, break things", right: "Metriken erzwingen" },
            c11: { char: "🏢 Facility Manager", text: "Die Home-Office-Ära ist vorbei. 5 Tage pro Woche Anwesenheitspflicht im Büro.", left: "Home-Office behalten", right: "Alle zurück ins Büro!" },
            c12: { char: "🌐 Justiziar", text: "Wir können User-Daten aggressiv tracken und für viel Profit an Werbenetzwerke verkaufen.", left: "Privatsphäre respektieren", right: "Daten sind das neue Öl" },
            c13: { char: "🤖 KI-Ingenieur", text: "Ich habe die QA-Abteilung automatisiert. Sollen wir sie feuern, um Geld zu sparen?", left: "Umschulen", right: "Entlassungen durchführen" },
            c14: { char: "🚀 Vorstandsmitglied", text: "Ein Konkurrent wird stark. Lass uns ihn für Milliarden kaufen, nur um ihn zu schließen.", left: "Fairer Wettbewerb", right: "Kaufen und zerstören" },
            c15: { char: "🌍 PR-Direktor", text: "Ein Whistleblower hat unsere Datenpraktiken geleakt! Die Presse stürzt sich darauf.", left: "Alles abstreiten", right: "Teure Entschuldigung" },
            c16: { char: "🛰️ Visionär", text: "Die Zukunft ist das Metaverse! Lass uns das gesamte Kerngeschäft auf VR umstellen.", left: "Fokus auf die Realität", right: "Ab ins Metaverse!" },
            c17: { char: "💾 Data Scientist", text: "Unsere KI generiert verstörende, fast bewusste Antworten. Sollen wir den Stecker ziehen?", left: "Lernen lassen", right: "Abschalten" },
            c18: { char: "🏃 Agile Coach", text: "Wir brauchen tägliche 2-Stunden-Standups für absolute Synergie.", left: "Zeitverschwendung.", right: "Synergie!" },
            c19: { char: "📈 Growth Hacker", text: "Ich kann 100k Bot-Follower kaufen, damit wir für Investoren riesig wirken.", left: "Bleib echt.", right: "Mach es." },
            c20: { char: "🐧 Open Source Dev", text: "Lass uns unsere Kern-Library Open Source machen! Bringt massiv Respekt.", left: "Bleibt proprietär.", right: "Open Source!" },
            c21: { char: "🧘 Wellness Guru", text: "Das Team ist gestresst. Lass uns ein Yoga-Retreat auf Bali finanzieren.", left: "Zu teuer.", right: "Namaste." },
            c22: { char: "📋 Compliance Officer", text: "Neue EU-Regeln erfordern einen massiven Umbau unserer Datenpipeline.", left: "Strafen zahlen.", right: "Sofort umbauen." },
            c23: { char: "🌍 Outsourcing Firm", text: "Wir können Kosten halbieren, wenn wir den Support auslagern.", left: "In-House behalten.", right: "Auslagern." },
            c26: { char: "💰 CFO", text: "Wir bereiten den Börsengang vor. Sollen wir die Zahlen... kreativ aufbereiten?", left: "Ehrliche Bücher.", right: "Zahlen schönen." },
            c27: { char: "🎯 Produktmanager", text: "Unser Freemium-Modell verbrennt Geld. Wir müssen auf ein aggressives Abo-Modell umsteigen.", left: "Freemium behalten.", right: "Abo-Modell einführen." },
            c28: { char: "🏆 Talentscout", text: "FAANG-Unternehmen werben unsere besten Entwickler mit irren Angeboten ab. Wir müssen mithalten.", left: "Lass sie gehen.", right: "Gehälter anpassen." },
            c29: { char: "📱 Mobile Lead", text: "Unsere App stürzt in 40% der Fälle ab. Wir müssen alles stoppen und von Grund auf neu bauen.", left: "Flicken und hoffen.", right: "Komplett neu bauen." },
            c30: { char: "🎪 Event Manager", text: "TechCrunch Disrupt will uns auf der Hauptbühne. Es kostet ein Vermögen, bringt aber massive Aufmerksamkeit.", left: "Event überspringen.", right: "Alles geben." },
            c31: { char: "🔬 F&E-Direktor", text: "Wir haben einen Durchbruch-Algorithmus entwickelt. Patentieren für Profit oder Open Source?", left: "Open Source.", right: "Patentieren." },
            c32: { char: "🌏 APAC-Direktor", text: "Wir brauchen Büros in Tokio und Singapur. Extrem teuer, aber öffnet riesige asiatische Märkte.", left: "Inland bleiben.", right: "Nach Asien expandieren." },
            c33: { char: "🛡️ CISO", text: "Eine staatliche Hackergruppe hat es auf uns abgesehen. Wir brauchen ein Cyber-Abwehrteam.", left: "Einfache Verteidigung.", right: "Cyber-Team aufbauen." },
            c34: { char: "🏛️ Lobbyist", text: "Neues Kartellrecht bedroht unser Geschäftsmodell. Wir müssen Millionen für Lobbying ausgeben.", left: "Regeln akzeptieren.", right: "Politiker beeinflussen." },
            c35: { char: "🌱 Nachhaltigkeitsbeauftragte", text: "Unsere Rechenzentren verbrauchen mehr Strom als manche Länder. Die Presse nennt uns Klimasünder.", left: "Kritiker ignorieren.", right: "Grün werden." },
            c36: { char: "🎓 Bildungsdirektor", text: "Wir sollten eine eigene interne Universität aufbauen, um Weltklasse-Ingenieure auszubilden.", left: "Zu teuer.", right: "Akademie aufbauen." },
            c37: { char: "🤝 M&A-Berater", text: "Ein europäischer Konkurrent schwächelt. Günstig kaufen, aber massiven Tech-Debt erben.", left: "Scheitern lassen.", right: "Übernehmen." },
            easter_egg: { char: "👾 Hacker Zero", text: "Ein mystisches Terminal öffnet sich. 'Gratis Krypto, wenn du die Geste kennst!'", left: "Terminal schließen", right: "Skript ausführen", up: "Krypto extrahieren!" },
            easter_egg_cat: { char: "🐱 Bürokatze", text: "Miau. (Die Katze verlangt Aufmerksamkeit und will nach oben.)", left: "Huscht!", right: "Ignorieren", up: "Katze streicheln!" },
            easter_egg_alien: { char: "👽 Kosmischer Investor", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. Nach OBEN wischen.", left: "Weglaufen", right: "Behörden rufen", up: "Geld annehmen!" },
            easter_egg_llama: { char: "🦙 Magisches Lama", text: "Ein mystisches Lama erscheint. 'Ich kann das Gleichgewicht wiederherstellen... vorübergehend.'", left: "Huscht!", right: "Ignorieren", up: "Gleichgewicht herstellen!" }
        }
    },
    it: {
        ui: {
            title: "TECH TYCOON", subtitle: "Guida la tua azienda IT da una startup in garage a un colosso Tech. Scorri per prendere decisioni!",
            start: "Fonda Startup", dead: "è stato licenziato", ruledFor: "È sopravvissuto per", sprints: "Sprint",
            restart: "Nuova Azienda (Sprint 0)", skipTime: "Usa monete per avanzare (5 🪙/Sprint):",
            skipBtn: "Salta", skipCost: "Costo", perfect: "Equilibrio Perfetto! +3 🪙", sprintPrefix: "Sprint",
            easterEggBonus: "Segreto Trovato! +5 🪙",
            llamaBonus: "Magia del Lama! Stat. resettate per 30s", llamaEnd: "Magia svanita!",
            revealStat: "Rivela il valore attuale", revealCost: "Costa 1 🪙", notEnoughCoins: "Monete insufficienti!", currentValue: "Valore attuale"
        },
        stats: {
            security: { title: "🔒 Sicurezza", description: "Quanto è protetta la tua azienda dalle minacce informatiche. Se scende a 0, il ransomware vince. Se raggiunge 100, nessuno riesce più a fare login." },
            morale: { title: "😊 Morale", description: "La soddisfazione generale del team. Se crolla, gli sviluppatori si dimettono. Se è troppo alta, nessuno lavora più." },
            tech: { title: "💻 Tecnologia", description: "Lo stato del tuo stack tecnologico. Trascuralo e il debito tecnico ti seppellirà. Automatizza troppo e l'IA ti sostituisce." },
            budget: { title: "💰 Budget", description: "La salute finanziaria dell'azienda. Vai in bancarotta e la partita è finita. Accumula troppo e gli investitori faranno una scalata ostile." }
        },
        eras: {
            startup: { name: "Startup in Garage", title: "Founder" }, scaleup: { name: "Scale-up", title: "CEO" },
            enterprise: { name: "Enterprise", title: "Direttore" }, unicorn: { name: "Unicorno", title: "CEO Unicorno" },
            global: { name: "Impero Globale", title: "CEO Globale" }, giant: { name: "Colosso Tech", title: "Overlord" }
        },
        reasons: {
            security_0: "Un attacco ransomware ha cancellato tutti i server. L'azienda è rovinata.", security_100: "La sicurezza è diventata così rigida che i dipendenti non riescono a fare login. Tutto bloccato.",
            morale_0: "Burnout al 100%. L'intero team di ingegneria si è dimesso per andare dalla concorrenza.", morale_100: "Tutti giocano a ping-pong e bevono kombucha. Nessuno lavora. Gli investitori scappano.",
            tech_0: "Il debito tecnico vi ha schiacciato. Il database principale ha preso fuoco e niente backup.", tech_100: "Hai automatizzato l'azienda con l'IA. L'IA ha capito che il CEO non serve e ti ha licenziato.",
            budget_0: "Avete finito i fondi e siete in bancarotta. Aggiorna il tuo CV.", budget_100: "Hai accumulato così tanto denaro che gli investitori hanno fatto una scalata ostile per incassare.",
            victory: "SPRINT 100 RAGGIUNTO! La tua azienda ha raggiunto la Singolarità Tecnologica. Trascendi il capitalismo e diventi un dio digitale. HAI VINTO!"
        },
        cards: {
            c1: { char: "👨‍💻 Lead Dev", text: "Dovremmo riscrivere tutto il backend usando un nuovo framework JavaScript di tendenza.", left: "Resta sul Vanilla", right: "Riscrivi tutto!" },
            c2: { char: "🔒 SysAdmin", text: "Voglio aumentare la sicurezza del firewall, ma bloccherà YouTube e Reddit ai dipendenti.", left: "Lascia internet libero", right: "Blocca tutto." },
            c3: { char: "💼 Investitore", text: "Gli sviluppatori si lamentano dei PC lenti. Compriamo MacBook top di gamma per tutti?", left: "Possono aspettare.", right: "Compra i laptop." },
            c4: { char: "📈 Sales Manager", text: "Ho promesso al cliente una feature enorme per venerdì. Ci aspetta un periodo di crunch pesante.", left: "Posticipa la scadenza.", right: "Falli lavorare di notte." },
            c5: { char: "☕ Stagista", text: "Sono tutti esausti. Possiamo comprare una macchina per l'espresso premium per l'area break?", left: "Caffè solubile.", right: "Approva l'acquisto." },
            c6: { char: "☁️ Cloud Architect", text: "I server on-premise stanno cedendo. Dobbiamo migrare tutto su AWS. È scalabile ma costoso.", left: "Resta on-prem.", right: "Migra sul Cloud." },
            c7: { char: "🕵️ Pen Tester", text: "Ho trovato una vulnerabilità zero-day critica. Dobbiamo fermare tutto e patchare subito.", left: "Prima le nuove feature.", right: "Ferma tutto e risolvi." },
            c8: { char: "🍕 HR Manager", text: "Il morale scende. Facciamo un pizza party obbligatorio venerdì sera per fare team building!", left: "Annulla il party.", right: "Ordina la pizza." },
            c9: { char: "🐛 QA Lead", text: "Abbiamo 500 bug aperti. Dobbiamo congelare le feature e passare lo sprint a risolvere il debito tecnico.", left: "Ignora i bug.", right: "Congela le feature." },
            c10: { char: "👔 VP of Engineering", text: "Dovremmo imporre metriche rigide del 100% di test coverage. Rallenterà le release ma migliora la qualità.", left: "Ship fast, break things.", right: "Imponi le metriche." },
            c11: { char: "🏢 Facility Manager", text: "L'era dello smart working è finita. Dobbiamo imporre il rientro in ufficio 5 giorni a settimana.", left: "Mantieni lo smart working.", right: "Tutti in ufficio!" },
            c12: { char: "🌐 Ufficio Legale", text: "Possiamo tracciare aggressivamente i dati degli utenti per vendere pubblicità mirata e fare profitti enormi.", left: "Rispetta la privacy.", right: "I dati sono il nuovo petrolio." },
            c13: { char: "🤖 Ingegnere IA", text: "Ho automatizzato con successo l'intero reparto QA. Dovremmo licenziarli per risparmiare soldi?", left: "Riqualificali.", right: "Procedi ai licenziamenti." },
            c14: { char: "🚀 Consigliere D'Amm.", text: "Una startup rivale sta crescendo. Compriamola per miliardi solo per farla chiudere.", left: "Competiamo lealmente.", right: "Acquisisci e distruggi." },
            c15: { char: "🌍 Direttore PR", text: "Un whistleblower ha diffuso le nostre pratiche oscure sui dati! La stampa ci sta massacrando.", left: "Nega tutto.", right: "Fai scuse costose." },
            c16: { char: "🛰️ Visionario", text: "Il futuro è il Metaverso! Spostiamo tutto il nostro core business sulla Realtà Virtuale.", left: "Concentrati sulla realtà.", right: "Verso il Metaverso!" },
            c17: { char: "💾 Data Scientist", text: "La nostra IA predittiva sta generando risposte inquietanti, sembra cosciente. Stacchiamo la spina?", left: "Lasciala imparare.", right: "Spegni tutto." },
            c18: { char: "🏃 Agile Coach", text: "Ci servono riunioni standup quotidiane di 2 ore per garantire una sinergia assoluta.", left: "Perdita di tempo.", right: "Sinergia!" },
            c19: { char: "📈 Growth Hacker", text: "Posso comprare 100k bot follower per farci sembrare enormi agli investitori.", left: "Resta onesto.", right: "Fallo." },
            c20: { char: "🐧 Open Source Dev", text: "Rendiamo open-source la nostra libreria core! Guadagneremo enorme rispetto.", left: "Resta proprietario.", right: "Open source!" },
            c21: { char: "🧘 Wellness Guru", text: "Il team è stressato. Finanziamo un ritiro spirituale obbligatorio a Bali.", left: "Troppo costoso.", right: "Namaste." },
            c22: { char: "📋 Compliance Officer", text: "Le nuove normative UE richiedono una revisione totale della nostra pipeline dati.", left: "Paga le multe.", right: "Adeguati subito." },
            c23: { char: "🌍 Outsourcing Firm", text: "Possiamo dimezzare i costi esternalizzando l'intero supporto clienti.", left: "Tieni in-house.", right: "Esternalizza." },
            c24: { char: "⚖️ Gov Regulator", text: "Avete un monopolio. Minacciamo di smembrare la vostra azienda.", left: "Combatti in tribunale.", right: "Fai lobbying (Corrompi)." },
            c25: { char: "💎 Crypto Bro", text: "Mettiamo tutta la tesoreria in una nostra memecoin iper-volatile!", left: "Assolutamente no.", right: "To the moon!" },
            c26: { char: "💰 CFO", text: "Ci stiamo preparando per la quotazione in borsa. Usiamo una contabilità... creativa per gonfiare la valutazione?", left: "Bilanci onesti.", right: "Truccare i numeri." },
            c27: { char: "🎯 Product Manager", text: "Il modello freemium ci dissangua. Dobbiamo passare a un modello di abbonamento aggressivo.", left: "Resta freemium.", right: "Passa all'abbonamento." },
            c28: { char: "🏆 Talent Scout", text: "Le grandi tech ci rubano i migliori ingegneri con offerte folli. Dobbiamo pareggiare gli stipendi.", left: "Lasciali andare.", right: "Pareggia le offerte." },
            c29: { char: "📱 Mobile Lead", text: "La nostra app crasha il 40% delle volte. Dobbiamo fermare tutto e ricostruirla da zero.", left: "Patch e preghiere.", right: "Ricostruzione totale." },
            c30: { char: "🎪 Event Manager", text: "TechCrunch Disrupt ci vuole sul palco principale. Costa una fortuna ma attirerebbe enorme attenzione.", left: "Salta l'evento.", right: "Tutto o niente." },
            c31: { char: "🔬 Direttore R&S", text: "Abbiamo sviluppato un algoritmo rivoluzionario. Lo brevettiamo per profitto o open source?", left: "Open source.", right: "Brevettalo." },
            c32: { char: "🌏 Direttore APAC", text: "Ci servono uffici a Tokyo e Singapore. Costosissimo ma apre mercati asiatici enormi.", left: "Resta nel paese.", right: "Espanditi in Asia." },
            c33: { char: "🛡️ CISO", text: "Un gruppo hacker governativo ci ha nel mirino. Servono difese cyber dedicate.", left: "Difese base.", right: "Costruisci il cyber team." },
            c34: { char: "🏛️ Lobbista", text: "Una nuova legge antitrust minaccia il nostro modello di business. Servono milioni in lobbying.", left: "Accetta le regole.", right: "Fai lobbying." },
            c35: { char: "🌱 Resp. Sostenibilità", text: "I nostri data center consumano più elettricità di interi paesi. La stampa ci chiama criminali del clima.", left: "Ignora le critiche.", right: "Diventa green." },
            c36: { char: "🎓 Direttore Formazione", text: "Dovremmo creare un'università interna per formare ingegneri di livello mondiale.", left: "Troppo costoso.", right: "Costruisci l'accademia." },
            c37: { char: "🤝 Consulente M&A", text: "Un concorrente europeo è in difficoltà. Possiamo acquisirlo a poco, ma erediteremo un debito tecnico enorme.", left: "Lascialo fallire.", right: "Acquisiscilo." },
            easter_egg: { char: "👾 Hacker Zero", text: "Si apre un terminale misterioso. 'Crypto gratis se conosci il gesto segreto!'", left: "Chiudi terminale", right: "Esegui script", up: "Estrai Crypto!" },
            easter_egg_cat: { char: "🐱 Gatto dell'Ufficio", text: "Miao. (Il gatto è saltato sulla tastiera ed esige coccole.)", left: "Sciò!", right: "Ignora", up: "Accarezza il gatto!" },
            easter_egg_alien: { char: "👽 Investitore Cosmico", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. Scorri in ALTO.", left: "Scappa", right: "Chiama le autorità", up: "Accetta i fondi!" },
            easter_egg_llama: { char: "🦙 Lama Magico", text: "Appare un Lama mistico. 'Posso ripristinare l'equilibrio... temporaneamente.'", left: "Sciò!", right: "Ignora", up: "Ripristina Equilibrio!" }
        }
    },
    es: {
        ui: {
            title: "TECH TYCOON", subtitle: "Lleva tu empresa TI desde un garaje a un gigante global. ¡Desliza para tomar decisiones!",
            start: "Lanzar Startup", dead: "fue despedido", ruledFor: "Sobrevivió por", sprints: "Sprints",
            restart: "Nueva Empresa (Sprint 0)", skipTime: "Usa Monedas para Avanzar (5 🪙/Sprint):",
            skipBtn: "Saltar", skipCost: "Costo", perfect: "¡Equilibrio Perfecto! +3 🪙", sprintPrefix: "Sprint",
            easterEggBonus: "¡Secreto Encontrado! +5 🪙",
            llamaBonus: "¡Magia de Llama! Stats reiniciados por 30s", llamaEnd: "¡Magia desvanecida!",
            revealStat: "Revelar valor actual", revealCost: "Cuesta 1 🪙", notEnoughCoins: "¡Monedas insuficientes!", currentValue: "Valor actual"
        },
        stats: {
            security: { title: "🔒 Seguridad", description: "Cuán protegida está tu empresa frente a ciberamenazas. Si llega a 0, el ransomware gana. Si llega a 100, nadie puede iniciar sesión." },
            morale: { title: "😊 Moral", description: "La satisfacción general de tu equipo. Si colapsa, los ingenieros renuncian. Si es demasiado alta, nadie trabaja." },
            tech: { title: "💻 Tecnología", description: "El estado de tu stack tecnológico. Descuídalo y la deuda técnica te aplastará. Automatiza demasiado y la IA te reemplaza." },
            budget: { title: "💰 Presupuesto", description: "La salud financiera de tu empresa. Quiébrate y el juego termina. Acumula demasiado y los inversores harán una adquisición hostil." }
        },
        eras: {
            startup: { name: "Startup de Garaje", title: "Fundador" }, scaleup: { name: "Scale-up", title: "CEO" },
            enterprise: { name: "Enterprise", title: "Director Ejecutivo" }, unicorn: { name: "Unicornio", title: "CEO Unicornio" },
            global: { name: "Imperio Global", title: "CEO Global" }, giant: { name: "Gigante Tech", title: "Amo Supremo" }
        },
        reasons: {
            security_0: "Un ransomware borró todos tus servidores. La empresa está arruinada.", security_100: "La seguridad es tan estricta que los empleados no pueden iniciar sesión. Operaciones detenidas.",
            morale_0: "Burnout al 100%. Todo el equipo de ingeniería renunció.", morale_100: "Todos juegan ping-pong. No se hace trabajo. Los inversores se retiraron.",
            tech_0: "La deuda técnica te aplastó. La base de datos se incendió sin copias de seguridad.", tech_100: "Automatizaste la empresa con IA. La IA decidió que no necesitaba un CEO y te despidió.",
            budget_0: "Te quedaste sin fondos y en bancarrota. Actualiza tu currículum.", budget_100: "Acumulaste tanto efectivo que los inversores organizaron una toma hostil.",
            victory: "¡SPRINT 100 ALCANZADO! Tu empresa logró la Singularidad Tecnológica. Trasciendes el capitalismo y te conviertes en un dios digital. ¡HAS GANADO!"
        },
        cards: {
            c1: { char: "👨‍💻 Lead Dev", text: "Deberíamos reescribir todo el backend usando un nuevo framework de JavaScript.", left: "Quédate con Vanilla", right: "¡Reescribe todo!" },
            c2: { char: "🔒 SysAdmin", text: "Quiero aumentar la seguridad del firewall, pero bloqueará YouTube y Reddit a los empleados.", left: "Internet abierto.", right: "Bloquéalo todo." },
            c3: { char: "💼 Inversor", text: "Los desarrolladores se quejan de PCs lentas. ¿Compramos MacBooks de gama alta?", left: "Pueden esperar.", right: "Compra las laptops." },
            c4: { char: "📈 Sales Manager", text: "Prometí al cliente una función masiva para el viernes. Significa mucho 'crunch time'.", left: "Pospón la fecha.", right: "Que trabajen de noche." },
            c5: { char: "☕ Becario", text: "Todos están exhaustos. ¿Podemos comprar una máquina de espresso premium?", left: "Café instantáneo.", right: "Aprueba la compra." },
            c6: { char: "☁️ Cloud Architect", text: "Nuestros servidores fallan. Debemos migrar a AWS. Es escalable pero muy caro.", left: "Mantén on-prem.", right: "Migra a la Nube." },
            c7: { char: "🕵️ Pen Tester", text: "Encontré una vulnerabilidad crítica zero-day. Debemos detener todo y parchearla.", left: "Funciones primero.", right: "Detén todo y arregla." },
            c8: { char: "🍕 HR Manager", text: "La moral baja. ¡Hagamos una fiesta obligatoria de pizza el viernes para subir el ánimo!", left: "Cancela la fiesta.", right: "Pide la pizza." },
            c9: { char: "🐛 QA Lead", text: "Tenemos 500 bugs abiertos. Debemos congelar funciones y arreglar la deuda técnica.", left: "Ignora los bugs.", right: "Congela funciones." },
            c10: { char: "👔 VP of Engineering", text: "Debemos imponer un 100% de test coverage. Será más lento pero con mejor código.", left: "Ship fast, break things.", right: "Impón las métricas." },
            c11: { char: "🏢 Facility Manager", text: "La era remota terminó. Debemos imponer el regreso a la oficina 5 días a la semana.", left: "Mantén trabajo remoto.", right: "¡Todos a la oficina!" },
            c12: { char: "🌐 Asesor Legal", text: "Podemos rastrear los datos de usuarios para vender anuncios y ganar millones.", left: "Respeta la privacidad.", right: "Los datos son petróleo." },
            c13: { char: "🤖 Ingeniero de IA", text: "Automaticé todo el departamento de QA. ¿Los despedimos para ahorrar dinero?", left: "Reentrénalos.", right: "Ejecuta los despidos." },
            c14: { char: "🚀 Miembro del Consejo", text: "Una startup rival crece. Comprémosla por miles de millones solo para cerrarla.", left: "Compite limpiamente.", right: "Adquiere y destruye." },
            c15: { char: "🌍 Director de PR", text: "¡Un filtrador expuso nuestras malas prácticas de datos! La prensa nos ataca.", left: "Níegalo todo.", right: "Disculpa costosa." },
            c16: { char: "🛰️ Visionario", text: "¡El futuro es el Metaverso! Pivotemos nuestro negocio a la Realidad Virtual.", left: "Concéntrate en la realidad.", right: "¡Hacia el Metaverso!" },
            c17: { char: "💾 Data Scientist", text: "Nuestra IA predictiva da respuestas perturbadoras y casi conscientes. ¿La apagamos?", left: "Déjala aprender.", right: "Apágala." },
            c18: { char: "🏃 Agile Coach", text: "Necesitamos reuniones diarias de 2 horas para asegurar sinergia absoluta.", left: "Pérdida de tiempo.", right: "¡Sinergia!" },
            c19: { char: "📈 Growth Hacker", text: "Puedo comprar 100k bots seguidores para parecer gigantes a los inversores.", left: "Mantenlo real.", right: "Hazlo." },
            c20: { char: "🐧 Open Source Dev", text: "¡Hagamos open-source nuestra librería principal! Ganaremos prestigio.", left: "Mantenlo privado.", right: "¡Open source!" },
            c21: { char: "🧘 Wellness Guru", text: "El equipo está estresado. Financiemos un retiro espiritual en Bali.", left: "Muy caro.", right: "Namaste." },
            c22: { char: "📋 Compliance Officer", text: "Las nuevas leyes de la UE exigen una reforma masiva de nuestros datos.", left: "Paga las multas.", right: "Cumplir de inmediato." },
            c23: { char: "🌍 Outsourcing Firm", text: "Podemos reducir costes a la mitad subcontratando el soporte al cliente.", left: "Mantenlo in-house.", right: "Subcontrata." },
            c24: { char: "⚖️ Gov Regulator", text: "Tienes un monopolio. Amenazamos con dividir tu empresa.", left: "Lucha en tribunales.", right: "Haz lobby (Soborna)." },
            c25: { char: "💎 Crypto Bro", text: "¡Metamos todos los fondos en nuestra propia memecoin volátil!", left: "Absolutamente no.", right: "¡To the moon!" },
            c26: { char: "💰 CFO", text: "Nos preparamos para la salida a bolsa. ¿Usamos contabilidad... creativa para inflar la valoración?", left: "Libros honestos.", right: "Maquillar los números." },
            c27: { char: "🎯 Product Manager", text: "El modelo freemium nos desangra. Necesitamos cambiar a un modelo de suscripción agresivo.", left: "Mantener freemium.", right: "Cambiar a suscripción." },
            c28: { char: "🏆 Cazatalentos", text: "Las grandes tech nos roban a los mejores ingenieros con ofertas locas. Debemos igualar sus salarios.", left: "Déjalos ir.", right: "Iguala las ofertas." },
            c29: { char: "📱 Mobile Lead", text: "Nuestra app se cuelga el 40% de las veces. Hay que parar todo y reconstruirla desde cero.", left: "Parchear y rezar.", right: "Reconstrucción total." },
            c30: { char: "🎪 Event Manager", text: "TechCrunch Disrupt nos quiere en el escenario principal. Cuesta una fortuna pero atraería mucha atención.", left: "Pasar del evento.", right: "A por todas." },
            c31: { char: "🔬 Director de I+D", text: "Hemos logrado un algoritmo revolucionario. ¿Lo patentamos o lo hacemos open source?", left: "Open source.", right: "Patentarlo." },
            c32: { char: "🌏 Director APAC", text: "Necesitamos oficinas en Tokio y Singapur. Carísimo, pero abre mercados asiáticos masivos.", left: "Quedarnos aquí.", right: "Expandir a Asia." },
            c33: { char: "🛡️ CISO", text: "Un grupo hacker de un estado-nación nos tiene en la mira. Necesitamos un equipo de ciberdefensa.", left: "Defensas básicas.", right: "Crear el equipo cyber." },
            c34: { char: "🏛️ Lobista", text: "Una nueva ley antimonopolio amenaza nuestro modelo. Necesitamos gastar millones en lobbying.", left: "Aceptar las reglas.", right: "Hacer lobbying." },
            c35: { char: "🌱 Oficial de Sostenibilidad", text: "Nuestros data centers consumen más electricidad que algunos países. La prensa nos llama criminales climáticos.", left: "Ignorar las críticas.", right: "Ser ecológicos." },
            c36: { char: "🎓 Director de Aprendizaje", text: "Deberíamos crear nuestra propia universidad interna para formar ingenieros de clase mundial.", left: "Muy caro.", right: "Crear la academia." },
            c37: { char: "🤝 Asesor de M&A", text: "Un competidor europeo está en problemas. Podemos adquirirlo barato, pero heredaríamos deuda técnica masiva.", left: "Que quiebre.", right: "Adquirirlo." },
            easter_egg: { char: "👾 Hacker Zero", text: "Se abre un terminal misterioso. '¡Cripto gratis si conoces el gesto!'", left: "Cerrar terminal", right: "Ejecutar script", up: "¡Extraer Cripto!" },
            easter_egg_cat: { char: "🐱 Gato de la Oficina", text: "Miau. (El gato saltó al teclado y exige atención.)", left: "¡Fuera!", right: "Ignorar", up: "¡Acariciar al gato!" },
            easter_egg_alien: { char: "👽 Inversor Cósmico", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. Desliza ARRIBA.", left: "Huir", right: "Llamar a las autoridades", up: "¡Aceptar fondos!" },
            easter_egg_llama: { char: "🦙 Llama Mágica", text: "Aparece una Llama mística. 'Puedo restaurar el equilibrio... temporalmente.'", left: "¡Fuera!", right: "Ignorar", up: "¡Restaurar Equilibrio!" }
        }
    },
    zh: {
        ui: {
            title: "科技大亨", subtitle: "带领你的IT公司从车库走向全球科技巨头。滑动卡牌做出高管决策！",
            start: "创立公司", dead: "被解雇了", ruledFor: "生存了", sprints: "个冲刺(Sprint)",
            restart: "新公司 (第0冲刺)", skipTime: "使用金币快进 (5 🪙 / 冲刺):",
            skipBtn: "跳过", skipCost: "消耗", perfect: "完美平衡！ +3 🪙", sprintPrefix: "第",
            easterEggBonus: "发现秘密！ +5 🪙",
            llamaBonus: "羊驼魔法！属性重置30秒", llamaEnd: "羊驼魔法消失！",
            revealStat: "揭示当前数值", revealCost: "消耗 1 🪙", notEnoughCoins: "金币不足！", currentValue: "当前数值"
        },
        stats: {
            security: { title: "🔒 安全", description: "公司抵御网络攻击的能力。降至0，勒索软件获胜；升至100，没人能登录系统。" },
            morale: { title: "😊 士气", description: "团队整体满意度。崩溃则工程师辞职；过高则无人干活，投资者撤资。" },
            tech: { title: "💻 技术", description: "技术栈状态与创新水平。忽视它，技术债务将把你压垮；过度自动化，AI 会取代你。" },
            budget: { title: "💰 资金", description: "公司的财务健康状况。破产则游戏结束；囤积过多则激进投资者发起恶意收购。" }
        },
        eras: {
            startup: { name: "车库创业", title: "创始人" }, scaleup: { name: "扩大规模", title: "CEO" },
            enterprise: { name: "企业级", title: "执行董事" }, unicorn: { name: "独角兽", title: "独角兽CEO" },
            global: { name: "全球帝国", title: "全球CEO" }, giant: { name: "科技巨头", title: "科技霸主" }
        },
        reasons: {
            security_0: "一场大规模的勒索软件攻击清空了你的所有服务器。公司完蛋了。", security_100: "安全极其严格，以至于员工根本无法登录。公司停止运转。",
            morale_0: "职业倦怠达到100%。整个工程团队辞职加入了竞争对手。", morale_100: "每个人都在打乒乓球。根本没人干活。投资者撤资了。",
            tech_0: "技术债务压垮了你。主数据库起火，而且没有备份。", tech_100: "你用AI完全自动化了公司。AI意识到它不需要CEO，把你解雇了。",
            budget_0: "你耗尽了资金，彻底破产了。是时候更新你的简历了。", budget_100: "你囤积了太多现金，激进投资者发起恶意收购套现。",
            victory: "到达第100个冲刺！你的公司实现了技术奇点。你超越了人类资本主义，成为了数字神明。你赢了！"
        },
        cards: {
            c1: { char: "👨‍💻 首席开发", text: "我们应该用最新的流行JavaScript框架重写整个后端。", left: "坚持用原生JS", right: "重写一切！" },
            c2: { char: "🔒 系统管理员", text: "我想加强防火墙安全，但会屏蔽员工的视频和社交网站。", left: "保持网络开放", right: "全部封锁" },
            c3: { char: "💼 投资者", text: "工程师们抱怨编译太慢。我们要给大家买顶配的MacBook吗？", left: "他们可以等", right: "买笔记本" },
            c4: { char: "📈 销售经理", text: "我向客户承诺周五交付一个大功能以拿下大单。这意味着严重的加班。", left: "推迟截止日期", right: "让团队熬夜干" },
            c5: { char: "☕ 实习生", text: "大家都精疲力尽了。我们能给休息室买一台高级意式咖啡机吗？", left: "喝速溶咖啡", right: "批准购买" },
            c6: { char: "☁️ 云架构师", text: "我们的本地服务器快不行了。我们需要迁移到AWS，可扩展但很贵。", left: "保留本地服务器", right: "迁移到云端" },
            c7: { char: "🕵️ 渗透测试员", text: "我发现了一个严重的零日漏洞。我们需要停止开发立刻修复。", left: "先发新功能", right: "放下一切去修复" },
            c8: { char: "🍕 HR经理", text: "士气低落。我们周五晚上办个强制参加的比萨派对来提振团队精神吧！", left: "取消派对", right: "订比萨" },
            c9: { char: "🐛 QA主管", text: "我们有500个未解决的bug。必须冻结新功能，花一个冲刺来修复技术债务。", left: "无视bug", right: "冻结新功能" },
            c10: { char: "👔 工程副总裁", text: "我们应强制执行100%的测试覆盖率。这会减慢交付，但提高代码质量。", left: "快速发布，打破常规", right: "强制执行指标" },
            c11: { char: "🏢 设施经理", text: "远程办公时代结束了。我们应该强制要求每周回办公室5天。", left: "保持远程办公", right: "所有人回办公室！" },
            c12: { char: "🌐 法律顾问", text: "我们可以对用户进行激进的后台跟踪，出售定向广告数据获取暴利。", left: "尊重用户隐私", right: "数据就是新石油" },
            c13: { char: "🤖 AI工程师", text: "我成功自动化了整个QA部门。我们是不是该把他们全裁了省钱？", left: "重新培训他们", right: "执行裁员" },
            c14: { char: "🚀 董事会成员", text: "一家竞争初创公司正在崛起。我们花几十亿买下他们，只为关掉他们。", left: "公平竞争", right: "收购并摧毁" },
            c15: { char: "🌍 公关总监", text: "有吹哨人泄露了我们不光彩的数据处理行为！新闻界闹翻天了。", left: "否认一切", right: "发布昂贵的道歉声明" },
            c16: { char: "🛰️ 远见者", text: "未来属于元宇宙！让我们把整个核心业务转向虚拟现实。", left: "关注现实", right: "进军元宇宙！" },
            c17: { char: "💾 数据科学家", text: "我们新的预测型AI正在生成令人不安的、类似有意识的回复。拔掉插头吗？", left: "让它学习", right: "关停它" },
            c18: { char: "🏃 敏捷教练", text: "我们需要每天2小时的站会来确保绝对的协同效应。", left: "浪费时间。", right: "发挥协同效应！" },
            c19: { char: "📈 增长黑客", text: "我可以买十万个机器人粉丝，让投资者觉得我们规模庞大。", left: "保持真实。", right: "干吧。" },
            c20: { char: "🐧 开源开发者", text: "把我们的核心库开源吧！我们会失去护城河，但能赢得开发者的尊重。", left: "保持闭源。", right: "开源它！" },
            c21: { char: "🧘 养生大师", text: "团队压力太大了。我们出资去巴厘岛办一个强制性的灵修周吧。", left: "太贵了。", right: "Namaste." },
            c22: { char: "📋 合规专员", text: "欧盟新的严格法规要求我们彻底重组整个数据管道。", left: "交罚款。", right: "立刻合规。" },
            c23: { char: "🌍 外包公司", text: "我们可以把整个客服团队外包出去，帮您削减一半成本。", left: "保留内部团队。", right: "外包出去。" },
            c24: { char: "⚖️ 政府监管员", text: "你们涉嫌非法垄断。我们正威胁要拆分你的公司。", left: "在法庭上抗争。", right: "游说(贿赂)他们。" },
            c25: { char: "💎 加密货币狂热者", text: "让我们把公司所有的资金都投入到我们自己发行的波动型Meme币中吧！", left: "绝对不行。", right: "To the moon!" },
            c26: { char: "💰 首席财务官", text: "我们正在筹备上市。要不要用点‘创意会计’来抬高估值？", left: "诚实记账", right: "美化数据" },
            c27: { char: "🎯 产品经理", text: "免费模式在烧钱。我们必须切换到激进的订阅模式。", left: "保持免费模式", right: "转向订阅制" },
            c28: { char: "🏆 猎头", text: "大厂正在用天价薪资挖我们最好的工程师。我们必须匹配他们的待遇。", left: "随他们去", right: "匹配报价" },
            c29: { char: "📱 移动端负责人", text: "我们的App有40%的崩溃率。必须停下一切，从头重建。", left: "修修补补", right: "全面重建" },
            c30: { char: "🎪 活动经理", text: "TechCrunch想让我们上主舞台。费用高昂，但能吸引巨大关注。", left: "跳过活动", right: "全力以赴" },
            c31: { char: "🔬 研发总监", text: "我们开发了突破性算法。是申请专利获利，还是开源赢得声誉？", left: "开源发布", right: "申请专利" },
            c32: { char: "🌏 亚太区总监", text: "我们需要在东京和新加坡设立办事处。非常昂贵，但能打开巨大的亚洲市场。", left: "留在国内", right: "扩展到亚洲" },
            c33: { char: "🛡️ 首席安全官", text: "一个国家级黑客组织正在针对我们。我们需要建立专门的网络战防御团队。", left: "基础防御就好", right: "组建网络战团队" },
            c34: { char: "🏛️ 说客", text: "新的反垄断法威胁着我们的整个商业模式。我们需要花数百万进行游说。", left: "接受规则", right: "游说政客" },
            c35: { char: "🌱 可持续发展官", text: "我们的数据中心耗电量超过了一些国家。媒体称我们为气候罪犯。", left: "无视批评", right: "走绿色路线" },
            c36: { char: "🎓 首席学习官", text: "我们应该建立自己的内部大学，从内部培养世界级工程人才。", left: "太贵了", right: "建立学院" },
            c37: { char: "🤝 并购顾问", text: "一个欧洲竞争对手陷入困境。我们可以低价收购，但会继承巨额技术债务。", left: "让他们倒闭", right: "收购他们" },
            easter_egg: { char: "👾 零号黑客", text: "一个神秘终端打开了。'如果你知道秘密手势，免费送你加密货币！'", left: "关闭终端", right: "运行脚本", up: "提取加密货币！" },
            easter_egg_cat: { char: "🐱 办公室猫", text: "喵。（猫跳到了你的键盘上，要求你抱抱。）", left: "走开！", right: "无视", up: "撸猫！" },
            easter_egg_alien: { char: "👽 宇宙投资者", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. 向上滑动以接受宇宙融资。", left: "逃跑", right: "呼叫有关部门", up: "接受投资！" },
            easter_egg_llama: { char: "🦙 神奇羊驼", text: "一只神秘的羊驼出现了。'我可以恢复平衡……暂时的。'", left: "走开！", right: "无视", up: "恢复平衡！" }
        }
    },
    ja: {
        ui: {
            title: "テックタイクーン", subtitle: "あなたのIT企業をガレージから世界的IT企業へと導け。スワイプで経営判断を下せ！",
            start: "スタートアップを立ち上げる", dead: "は解雇された", ruledFor: "生存期間", sprints: "スプリント",
            restart: "新しい会社 (スプリント 0)", skipTime: "コインを使って早送り (5 🪙/スプリント):",
            skipBtn: "スキップ", skipCost: "コスト", perfect: "パーフェクトバランス！ +3 🪙", sprintPrefix: "第",
            easterEggBonus: "秘密を発見！ +5 🪙",
            llamaBonus: "リャマの魔法！30秒間ステータスリセット", llamaEnd: "魔法が解けた！",
            revealStat: "現在の値を見る", revealCost: "1 🪙 消費", notEnoughCoins: "コインが足りません！", currentValue: "現在の値"
        },
        stats: {
            security: { title: "🔒 セキュリティ", description: "サイバー攻撃に対する防御力。0になるとランサムウェアに負け、100になると誰もログインできない。" },
            morale: { title: "😊 モラル", description: "チームの満足度。崩壊するとエンジニアが辞め、高すぎると誰も働かなくなる。" },
            tech: { title: "💻 テクノロジー", description: "技術スタックとイノベーションの水準。放置すると技術的負債で潰れ、自動化しすぎるとAIに解雇される。" },
            budget: { title: "💰 予算", description: "会社の財務健全性と資金繰り。破産するとゲームオーバー。溜め込みすぎると敵対的買収を受ける。" }
        },
        eras: {
            startup: { name: "ガレージスタートアップ", title: "創業者" }, scaleup: { name: "スケールアップ", title: "CEO" },
            enterprise: { name: "大企業", title: "専務" }, unicorn: { name: "ユニコーン", title: "ユニコーンCEO" },
            global: { name: "グローバル帝国", title: "グローバルCEO" }, giant: { name: "テックジャイアント", title: "テックの覇王" }
        },
        reasons: {
            security_0: "大規模なランサムウェア攻撃でサーバーが消滅しました。会社は破滅です。", security_100: "セキュリティが厳しすぎて社員がログインできません。業務が停止しました。",
            morale_0: "燃え尽き症候群が100%に。エンジニアチーム全員が辞め、競合他社に移りました。", morale_100: "誰もが卓球ばかりしています。仕事が進みません。投資家は撤退しました。",
            tech_0: "技術的負債に押し潰されました。メインDBが炎上し、バックアップもありません。", tech_100: "AIで会社を完全自動化しました。AIはCEOが不要だと判断し、あなたを解雇しました。",
            budget_0: "資金が底をつき、完全に倒産しました。履歴書を更新する時間です。", budget_100: "現金を溜め込みすぎたため、投資家が利益を得るために敵対的買収を行いました。",
            victory: "スプリント100到達！あなたの会社は技術的特異点に達しました。資本主義を超越したデジタルゴッドの誕生です。あなたの勝ち！"
        },
        cards: {
            c1: { char: "👨‍💻 リードエンジニア", text: "最新のJavaScriptフレームワークを使ってバックエンドを書き直すべきです。", left: "Vanilla JSのままで", right: "すべて書き直せ！" },
            c2: { char: "🔒 社内SE", text: "ファイアウォールを強化したいですが、社員のYouTubeやRedditも見られなくなります。", left: "ネットは開放する", right: "すべてブロック" },
            c3: { char: "💼 投資家", text: "エンジニアがPCの遅さに不満を持っています。最高級のMacBookを買いますか？", left: "後回しだ", right: "PCを買う" },
            c4: { char: "📈 営業部長", text: "大型契約を取るために金曜までに巨大機能を納品すると約束しました。激しいデスマーチになります。", left: "納期を遅らせる", right: "徹夜でやらせる" },
            c5: { char: "☕ インターン", text: "みんな疲弊しています。休憩室に高級エスプレッソマシンを買いませんか？", left: "インスタントで十分", right: "購入を承認する" },
            c6: { char: "☁️ クラウド設計者", text: "自社サーバーが限界です。AWSに移行する必要がありますが、高額です。", left: "オンプレミス維持", right: "クラウドへ移行" },
            c7: { char: "🕵️ ペンテスター", text: "致命的なゼロデイ脆弱性を発見しました。開発を止めて直ちにパッチを当てる必要があります。", left: "新機能が先だ", right: "すべて止めて修正" },
            c8: { char: "🍕 人事部長", text: "士気が低下しています。金曜の夜に強制参加のピザパーティーを開きましょう！", left: "パーティーを中止", right: "ピザを注文する" },
            c9: { char: "🐛 QAリード", text: "500個のバグがあります。機能を凍結し、技術的負債の解消に1スプリント費やすべきです。", left: "バグは無視する", right: "機能を凍結する" },
            c10: { char: "👔 開発責任者", text: "テストカバレッジ100%を厳格に義務付けるべきです。遅くなりますが品質は上がります。", left: "とにかく早く出せ", right: "指標を義務付ける" },
            c11: { char: "🏢 施設管理者", text: "リモートワークの時代は終わりました。週5日のオフィス出社を義務付けるべきです。", left: "リモートを維持", right: "全員オフィスに戻れ！" },
            c12: { char: "🌐 法務顧問", text: "ユーザーデータを裏で追跡し、ターゲティング広告のデータを売れば莫大な利益が出ます。", left: "プライバシーを尊重", right: "データは新しい石油だ" },
            c13: { char: "🤖 AIエンジニア", text: "QA部門の完全自動化に成功しました。コスト削減のために彼らを全員解雇しますか？", left: "再教育する", right: "解雇を実行する" },
            c14: { char: "🚀 取締役", text: "ライバル企業が成長しています。潰すためだけに何十億で買収しましょう。", left: "公平に競争する", right: "買収して解体する" },
            c15: { char: "🌍 広報部長", text: "内部告発者が我々の怪しいデータ管理をリークしました！マスコミが大騒ぎです。", left: "すべて否定する", right: "高額な謝罪をする" },
            c16: { char: "🛰️ ビジョナリー", text: "未来はメタバースです！中核事業をすべてVRにピボットしましょう。", left: "現実を見る", right: "メタバースへ！" },
            c17: { char: "💾 データサイエンティスト", text: "我々の予測AIが、自我を持ったような不気味な反応をしています。電源を抜きますか？", left: "学習を続けさせる", right: "シャットダウンする" },
            c18: { char: "🏃 アジャイルコーチ", text: "完璧なシナジーを生み出すため、毎日2時間のスタンドアップミーティングが必要です。", left: "時間の無駄だ。", right: "シナジーだ！" },
            c19: { char: "📈 グロースハッカー", text: "投資家を騙すために、10万人のボットフォロワーを買うことができます。", left: "誠実であれ。", right: "やれ。" },
            c20: { char: "🐧 OSS開発者", text: "コアライブラリをオープンソース化しましょう！尊敬を集めることができます。", left: "非公開を貫く。", right: "オープンソースだ！" },
            c21: { char: "🧘 ウェルネスの達人", text: "チームは疲弊しています。バリ島での1週間のスピリチュアル合宿に資金を出しましょう。", left: "高すぎる。", right: "ナマステ。" },
            c22: { char: "📋 コンプライアンス担当", text: "EUの新しい厳格な規制により、データパイプラインの全面的な見直しが必要です。", left: "罰金を払う。", right: "直ちに従う。" },
            c23: { char: "🌍 アウトソーシング企業", text: "カスタマーサポートをすべて外注すれば、コストを半分に抑えられます。", left: "自社で維持する。", right: "外注する。" },
            c24: { char: "⚖️ 政府の規制当局", text: "あなたは違法な独占をしています。会社を解体すると脅告されています。", left: "法廷で争う。", right: "ロビー活動（賄賂）をする。" },
            c25: { char: "💎 仮想通貨信者", text: "会社の資金をすべて、独自のボラティリティの高いミームコインに投資しましょう！", left: "絶対にダメだ。", right: "To the moon!" },
            c26: { char: "💰 CFO", text: "IPOの準備中です。評価額を水増しするために…創造的な会計処理をしますか？", left: "正直な帳簿を維持", right: "数字を粉飾する" },
            c27: { char: "🎯 プロダクトマネージャー", text: "フリーミアムモデルで大赤字です。アグレッシブなサブスクモデルに切り替える必要があります。", left: "フリーミアム維持", right: "サブスクに移行" },
            c28: { char: "🏆 タレントスカウト", text: "GAFA企業が最高のエンジニアを破格の条件で引き抜いています。給与を合わせる必要があります。", left: "行かせてあげる", right: "条件を合わせる" },
            c29: { char: "📱 モバイルリード", text: "アプリが40%の確率で落ちます。全てを止めてゼロから作り直す必要があります。", left: "パッチで凌ぐ", right: "完全に作り直す" },
            c30: { char: "🎪 イベントマネージャー", text: "TechCrunch Disruptのメインステージに招待されました。莫大な費用ですが注目を集められます。", left: "イベントを見送る", right: "全力で挑む" },
            c31: { char: "🔬 R&Dディレクター", text: "画期的なアルゴリズムを開発しました。特許で利益を得るか、OSSで信頼を得るか？", left: "オープンソースにする", right: "特許を取得する" },
            c32: { char: "🌏 アジア太平洋地域担当", text: "東京とシンガポールにオフィスが必要です。莫大な費用ですがアジア市場が開けます。", left: "国内に留まる", right: "アジアに進出する" },
            c33: { char: "🛡️ CISO", text: "国家支援のハッカー集団が我が社を標的にしています。サイバー防衛チームが必要です。", left: "基本的な防御のみ", right: "サイバーチームを構築" },
            c34: { char: "🏛️ ロビイスト", text: "新しい独占禁止法がビジネスモデルを脅かしています。ロビー活動に数百万が必要です。", left: "規制を受け入れる", right: "政治家にロビー活動" },
            c35: { char: "🌱 サステナビリティ責任者", text: "データセンターの電力消費量が一部の国を超えています。マスコミに気候犯罪者と呼ばれています。", left: "批判を無視する", right: "グリーン化する" },
            c36: { char: "🎓 最高学習責任者", text: "世界レベルのエンジニアを社内で育成するため、独自の社内大学を設立すべきです。", left: "高すぎる", right: "アカデミーを設立" },
            c37: { char: "🤝 M&Aアドバイザー", text: "欧州の競合が苦境にあります。安く買収できますが、膘大な技術的負債を引き継ぎます。", left: "破綻させる", right: "買収する" },
            easter_egg: { char: "👾 ハッカーゼロ", text: "謎のターミナルが開いた。「秘密のジェスチャーを知っていれば仮想通貨をやるよ！」", left: "ターミナルを閉じる", right: "スクリプト実行", up: "仮想通貨を抽出！" },
            easter_egg_cat: { char: "🐱 オフィスの猫", text: "ニャー。(猫がキーボードに飛び乗り、撫でるよう要求している)", left: "シッシッ！", right: "無視する", up: "猫を撫でる！" },
            easter_egg_alien: { char: "👽 宇宙の投資家", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. 上にスワイプ。", left: "逃げる", right: "当局を呼ぶ", up: "資金を受け取る！" },
            easter_egg_llama: { char: "🦙 魔法のリャマ", text: "神秘的なリャマが現れた。「バランスを取り戻してあげよう…一時的にね。」", left: "シッシッ！", right: "無視する", up: "バランスを回復！" }
        }
    },
    ko: {
        ui: {
            title: "테크 타이쿤", subtitle: "차고지 스타트업을 글로벌 테크 거인으로 성장시키세요. 화면을 쓸어 경영 결정을 내리세요!",
            start: "스타트업 설립", dead: "해고되었습니다", ruledFor: "생존 기간", sprints: "스프린트",
            restart: "새 회사 (스프린트 0)", skipTime: "코인으로 빨리 감기 (5 🪙/스프린트):",
            skipBtn: "건너뛰기", skipCost: "비용", perfect: "완벽한 균형! +3 🪙", sprintPrefix: "제",
            easterEggBonus: "비밀 발견! +5 🪙",
            llamaBonus: "라마의 마법! 30초간 스탯 리셋", llamaEnd: "마법이 풀렸습니다!",
            revealStat: "현재 값 공개", revealCost: "1 🪙 소모", notEnoughCoins: "코인이 부족합니다!", currentValue: "현재 값"
        },
        stats: {
            security: { title: "🔒 보안", description: "사이버 위협으로부터 회사를 보호하는 수준. 0이 되면 랜섬웨어가 이기고, 100이 되면 아무도 로그인하지 못한다." },
            morale: { title: "😊 사기", description: "팀의 전반적인 만족도. 무너지면 엔지니어들이 퇴직하고, 너무 높으면 아무도 일하지 않는다." },
            tech: { title: "💻 기술", description: "기술 스택의 상태와 혁신 수준. 방치하면 기술 부채에 짓눌리고, 과도하게 자동화하면 AI가 당신을 해고한다." },
            budget: { title: "💰 예산", description: "회사의 재정 건전성. 파산하면 게임 오버. 너무 많이 쌓아두면 투자자들이 적대적 인수합병을 시도한다." }
        },
        eras: {
            startup: { name: "차고지 스타트업", title: "창업자" }, scaleup: { name: "스케일업", title: "CEO" },
            enterprise: { name: "엔터프라이즈", title: "임원" }, unicorn: { name: "유니콘", title: "유니콘 CEO" },
            global: { name: "글로벌 제국", title: "글로벌 CEO" }, giant: { name: "테크 거인", title: "테크 군주" }
        },
        reasons: {
            security_0: "대규모 랜섬웨어 공격으로 모든 서버가 날아갔습니다. 회사는 파산했습니다.", security_100: "보안이 너무 엄격해져 직원들이 로그인조차 할 수 없습니다. 업무가 마비되었습니다.",
            morale_0: "번아웃이 100%에 달했습니다. 엔지니어 팀 전체가 사표를 내고 경쟁사로 갔습니다.", morale_100: "모두가 탁구만 치며 놉니다. 일이 진행되지 않아 투자자들이 자금을 회수했습니다.",
            tech_0: "기술 부채가 회사를 짓눌렀습니다. 메인 DB에 화재가 났고 백업도 없습니다.", tech_100: "회사를 AI로 완벽하게 자동화했습니다. AI는 CEO가 필요 없다는 것을 깨닫고 당신을 해고했습니다.",
            budget_0: "자금이 바닥나 완전 파산했습니다. 이력서를 업데이트할 시간입니다.", budget_100: "현금을 너무 많이 쌓아둔 탓에 행동주의 투자자들이 적대적 인수합병을 진행했습니다.",
            victory: "스프린트 100 도달! 당신의 회사는 기술적 특이점을 달성했습니다. 인류의 자본주의를 초월하여 디지털 신이 되었습니다. 승리했습니다!"
        },
        cards: {
            c1: { char: "👨‍💻 수석 개발자", text: "유행하는 새 자바스크립트 프레임워크로 백엔드를 전부 다시 써야 합니다.", left: "그냥 쓰던 거 쓰자", right: "전부 다시 작성해!" },
            c2: { char: "🔒 시스템 관리자", text: "방화벽 보안을 강화하고 싶은데, 그러면 직원들의 유튜브와 레딧이 차단됩니다.", left: "인터넷은 열어둬", right: "전부 차단해" },
            c3: { char: "💼 투자자", text: "엔지니어들이 컴파일이 너무 느리다고 불평합니다. 최고급 맥북을 사줄까요?", left: "조금 기다려", right: "노트북 구매해" },
            c4: { char: "📈 영업 관리자", text: "큰 계약을 따내려고 금요일까지 거대한 기능을 개발해주기로 약속했습니다. 엄청난 야근이 필요합니다.", left: "마감일 연기해", right: "팀에게 철야를 지시해" },
            c5: { char: "☕ 인턴", text: "모두가 지쳐있습니다. 휴게실에 최고급 에스프레소 머신을 사도 될까요?", left: "인스턴트 커피나 마셔", right: "구매 승인" },
            c6: { char: "☁️ 클라우드 아키텍트", text: "온프레미스 서버가 한계입니다. AWS로 마이그레이션해야 합니다. 확장성은 좋지만 매우 비쌉니다.", left: "온프레미스 유지", right: "클라우드로 이전" },
            c7: { char: "🕵️ 모의 해커", text: "치명적인 제로데이 취약점을 발견했습니다. 즉시 모든 개발을 멈추고 패치해야 합니다.", left: "새 기능이 먼저야", right: "다 멈추고 고쳐" },
            c8: { char: "🍕 인사 관리자", text: "사기가 떨어지고 있습니다. 금요일 저녁에 의무 참석 피자 파티를 열어 팀워크를 다지죠!", left: "파티 취소해", right: "피자 주문해" },
            c9: { char: "🐛 QA 리더", text: "열려있는 버그가 500개나 됩니다. 기능을 동결하고 이번 스프린트는 기술 부채 해결에 써야 합니다.", left: "버그 무시해", right: "기능 개발 동결" },
            c10: { char: "👔 엔지니어링 부사장", text: "테스트 커버리지 100%를 엄격하게 적용해야 합니다. 배포는 느려지겠지만 코드 품질은 좋아집니다.", left: "일단 빨리 배포해", right: "엄격하게 적용해" },
            c11: { char: "🏢 시설 관리자", text: "재택근무 시대는 끝났습니다. 주 5일 사무실 출근을 의무화해야 합니다.", left: "재택근무 유지", right: "모두 사무실로 돌아와!" },
            c12: { char: "🌐 법무 자문", text: "유저 데이터를 몰래 추적해서 타겟 광고로 팔면 엄청난 수익을 얻을 수 있습니다.", left: "사용자 프라이버시 존중", right: "데이터가 곧 돈이다" },
            c13: { char: "🤖 AI 엔지니어", text: "QA 부서 전체를 자동화하는 데 성공했습니다. 돈을 아끼기 위해 다 해고할까요?", left: "재교육 시켜", right: "해고 진행해" },
            c14: { char: "🚀 이사회 멤버", text: "경쟁 스타트업이 크고 있습니다. 수십억을 주고 인수해서 그냥 폐업시켜 버리죠.", left: "공정하게 경쟁해", right: "인수해서 없애버려" },
            c15: { char: "🌍 PR 디렉터", text: "내부 고발자가 우리의 은밀한 데이터 관행을 유출했습니다! 언론이 난리가 났습니다.", left: "전부 부인해", right: "비싼 사과문을 내" },
            c16: { char: "🛰️ 비저너리", text: "미래는 메타버스입니다! 회사의 핵심 비즈니스를 모두 VR로 전환합시다.", left: "현실에 집중해", right: "메타버스로!" },
            c17: { char: "💾 데이터 과학자", text: "우리의 새 예측형 AI가 자아를 가진 듯한 소름 끼치는 답변을 생성하고 있습니다. 전원을 내릴까요?", left: "계속 학습시켜", right: "시스템 종료해" },
            c18: { char: "🏃 애자일 코치", text: "완벽한 시너지를 위해 매일 2시간씩 스탠드업 미팅을 해야 합니다.", left: "시간 낭비야.", right: "시너지를 내자!" },
            c19: { char: "📈 그로스 해커", text: "봇 팔로워 10만 명을 사서 투자자들에게 우리가 엄청 커 보이게 할 수 있습니다.", left: "진정성을 지켜.", right: "진행해." },
            c20: { char: "🐧 오픈소스 개발자", text: "핵심 라이브러리를 오픈소스로 공개합시다! 해자는 잃겠지만 개발자들의 존경을 얻을 것입니다.", left: "독점 상태로 유지해.", right: "오픈소스화 해!" },
            c21: { char: "🧘 웰니스 전문가", text: "팀이 지쳐있습니다. 발리에서 의무적으로 일주일간 영적 수련회를 개최합시다.", left: "너무 비싸.", right: "나마스떼." },
            c22: { char: "📋 규정 준수 책임자", text: "EU의 새로운 엄격한 규정 때문에 데이터 파이프라인 전체를 대대적으로 수정해야 합니다.", left: "벌금을 내겠다.", right: "즉시 준수해." },
            c23: { char: "🌍 아웃소싱 업체", text: "고객 지원 팀 전체를 아웃소싱하면 비용을 절반으로 줄일 수 있습니다.", left: "내부에 유지해.", right: "아웃소싱 해." },
            c24: { char: "⚖️ 정부 규제 당국", text: "당신은 불법 독점을 하고 있습니다. 회사를 분할하겠다고 위협하고 있습니다.", left: "법정에서 싸운다.", right: "로비(뇌물)를 한다." },
            c25: { char: "💎 암호화폐 열성가", text: "회사 자금 전부를 변동성이 큰 자체 밈코인에 투자합시다!", left: "절대 안 돼.", right: "달까지 가즈아!" },
            c26: { char: "💰 CFO", text: "IPO를 준비 중입니다. 기업 가치를 부풀리기 위해 '창의적 회계'를 사용할까요?", left: "정직한 회계 유지", right: "숫자를 꾸미자" },
            c27: { char: "🎯 프로덕트 매니저", text: "프리미엄 모델이 돈을 갉아먹고 있습니다. 과감한 구독 모델로 전환해야 합니다.", left: "프리미엄 유지", right: "구독 모델로 전환" },
            c28: { char: "🏆 인재 스카우트", text: "대형 테크 기업들이 최고의 엔지니어들을 미친 조건으로 빼가고 있습니다. 연봉을 맞춰야 합니다.", left: "보내춰", right: "조건을 맞춰" },
            c29: { char: "📱 모바일 리드", text: "앱이 40%의 확률로 크래시됩니다. 모든 것을 멈추고 처음부터 다시 만들어야 합니다.", left: "패치로 버터", right: "완전히 재구축" },
            c30: { char: "🎪 이벤트 매니저", text: "TechCrunch Disrupt 메인 스테이지에 서달라는 초대를 받았습니다. 엄청난 비용이지만 큰 관심을 끌 수 있습니다.", left: "이벤트 건너뛰기", right: "올인하자" },
            c31: { char: "🔬 R&D 디렉터", text: "획기적인 알고리즘을 개발했습니다. 특허를 내서 수익을 낼까요, 오픈소스로 명성을 쌓을까요?", left: "오픈소스로 공개", right: "특허 출원" },
            c32: { char: "🌏 아시아태평양 디렉터", text: "도쿄와 싱가포르에 사무실이 필요합니다. 엄청나게 비싸지만 거대한 아시아 시장이 열립니다.", left: "국내에 머물자", right: "아시아로 확장" },
            c33: { char: "🛡️ CISO", text: "국가 지원 해커 그룹이 우리를 표적으로 삼고 있습니다. 전담 사이버 방어 팀이 필요합니다.", left: "기본 방어만", right: "사이버 팀 구축" },
            c34: { char: "🏛️ 로비스트", text: "새 반독점법이 우리의 사업 모델을 위협합니다. 수백만 달러를 로비에 써야 합니다.", left: "규칙을 수용해", right: "정치인에 로비해" },
            c35: { char: "🌱 지속가능성 책임자", text: "우리 데이터 센터가 일부 국가보다 더 많은 전력을 소비합니다. 언론이 우리를 기후 범죄자라고 부릅니다.", left: "비판 무시", right: "친환경으로 전환" },
            c36: { char: "🎓 최고학습책임자", text: "세계 수준의 엔지니어를 내부에서 키우기 위해 자체 기업 대학을 만들어야 합니다.", left: "너무 비싸", right: "아카데미 설립" },
            c37: { char: "🤝 M&A 자문", text: "유럽의 경쟁사가 어려움에 처해 있습니다. 저렴하게 인수할 수 있지만 거대한 기술 부채를 떠안게 됩니다.", left: "실패하게 두", right: "인수하자" },
            easter_egg: { char: "👾 해커 제로", text: "알 수 없는 터미널이 열렸습니다. '비밀 제스처를 알면 공짜 크립토를 주지!'", left: "터미널 닫기", right: "스크립트 실행", up: "크립토 추출!" },
            easter_egg_cat: { char: "🐱 오피스 고양이", text: "야옹. (고양이가 키보드 위로 뛰어올라 쓰다듬어 달라고 요구합니다.)", left: "저리 가!", right: "무시한다", up: "고양이를 쓰다듬는다!" },
            easter_egg_alien: { char: "👽 우주 투자자", text: "⍙⟒ ⍜⎎⎎⟒⍀ ☌⏃⌰⏃☊⏁⟟☊ ☊⍀⟒⎅⟟⏁⌇. 위로 스와이프 하세요.", left: "도망친다", right: "당국에 신고한다", up: "투자를 수락한다!" },
            easter_egg_llama: { char: "🦙 마법의 라마", text: "신비한 라마가 나타났습니다. '균형을 되찾아 주지... 일시적으로.'", left: "저리 가!", right: "무시한다", up: "균형 회복!" }
        }
    }
};
